import "../styles/globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/layout/Footer/Footer";



export const metadata = {
  title: "Tourism in Myanmar",
  description: "Generated by create next app",
  icons: {
    icon: [
      
      { url: '/icons/favicon.ico', sizes: 'any', type: 'image/x-icon' }, 
      
      { url: '/icons/favicon-32x32.png', sizes: '32x32', type: 'image/png' }, 
      
      { url: '/icons/favicon-16x16.png', sizes: '16x16', type: 'image/png' }, 
    ],
    // For Apple devices
    apple: [
      { url: '/icons/apple-touch-icon.png', sizes: '180x180', type: 'image/png' },
    ],
   
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        
      >
        <header>
          <Navbar/>
        </header>
        <main className="main-container">
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
