import "../styles/globals.css";
import Navbar from "@/components/Navbar";



export const metadata = {
  title: "Tourism in Myanmar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        
      >
        <header>
          <Navbar/>
        </header>
        <main className="main-container">
          {children}
        </main>
      </body>
    </html>
  );
}
